language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

before_install:
  - SED_GET_PY='s/[^0-9]//g;s/.//3g;2s/.*/py/;1!G;h;$!d;s/y.2./y/;s/y.3./y3/'
  - PY=$(python -V 2>&1 | sed "$SED_GET_PY")
  - TOX=tox
  - test $PY != 32 || TOX='virtualenv<14 tox<3'
  - test $PY != 33 -a $PY != 26 || TOX='virtualenv<15.2 tox<3'
  - export TOXENV=py$PY

install:
  - pip install $TOX
  - tox --notest

script:
  - tox

notifications:
    email: false
